<a href="https://colab.research.google.com/github/johyunkang/py_pandas/blob/main/python_ml_guide_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3], [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)




array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1:1차원, array2:2차원, array3: 2차원
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


type 변경


In [2]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
print(array_float1)
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1.1 2.1 3.1]
[1 2 3] int32


**ndarray를 편리하게 생성하기 - arrange, zeros, ones**




In [15]:
# arange() TO 값까지
seq_array = np.arange(10)
print(seq_array)

# arange() from to
seq_array1 = np.arange(1, 10)
print(seq_array1)

# arange() from to interval
seq_array2 = np.arange(1,10, 2)
print(seq_array2)

print('--------------------------------------------------')
# zeros()
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print('zero_array type:', zero_array.dtype, 'shape:', zero_array.shape)

print('--------------------------------------------------')
# ones()
one_array = np.ones((3,2))
print(one_array)
print('ones type:', one_array.dtype, 'shape:', one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
--------------------------------------------------
[[0 0]
 [0 0]
 [0 0]]
zero_array type: int32 shape: (3, 2)
--------------------------------------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
ones type: float64 shape: (3, 2)


**차원과 크기를 변경하는 reshape()**

In [17]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

# -1 인자는 변경 가능한 숫자로 자동대입 
# reshape(2,5) 를 입력해야 하지만 열 인자에 5를 넣었을때 가능한 행 인자는 2 이기에 -1 이 2로 자동대입 됨
array4 = array1.reshape(-1,5)
print('array4:\n', array4)

array5 = array1.reshape(5,-1)
print('array5:\n', array5)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array5:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
