<a href="https://colab.research.google.com/github/johyunkang/py_pandas/blob/main/python_ml_guide_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3], [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)




array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1:1차원, array2:2차원, array3: 2차원
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


type 변경


In [2]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
print(array_float1)
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1.1 2.1 3.1]
[1 2 3] int32


**ndarray를 편리하게 생성하기 - arrange, zeros, ones**




In [3]:
# arange() TO 값까지
seq_array = np.arange(10)
print(seq_array)

# arange() from to
seq_array1 = np.arange(1, 10)
print(seq_array1)

# arange() from to interval
seq_array2 = np.arange(1,10, 2)
print(seq_array2)

print('--------------------------------------------------')
# zeros()
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print('zero_array type:', zero_array.dtype, 'shape:', zero_array.shape)

print('--------------------------------------------------')
# ones()
one_array = np.ones((3,2))
print(one_array)
print('ones type:', one_array.dtype, 'shape:', one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
--------------------------------------------------
[[0 0]
 [0 0]
 [0 0]]
zero_array type: int32 shape: (3, 2)
--------------------------------------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
ones type: float64 shape: (3, 2)


**차원과 크기를 변경하는 reshape()**

In [4]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

# -1 인자는 변경 가능한 숫자로 자동대입 
# reshape(2,5) 를 입력해야 하지만 열 인자에 5를 넣었을때 가능한 행 인자는 2 이기에 -1 이 2로 자동대입 됨
array4 = array1.reshape(-1,5)
print('array4:\n', array4)

array5 = array1.reshape(5,-1)
print('array5:\n', array5)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array5:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Indexing


In [5]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]
print('value:', value)
print(type(value))

array1[8] = 1
array1[7] = 5
print('array1:', array1)


array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('row=0, col=0 index 값:', array2d[0,0])
print('row=2, col=2 index 값:', array2d[2,2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
array1: [1 2 3 4 5 6 7 5 1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
row=0, col=0 index 값: 1
row=2, col=2 index 값: 9


## 행렬의 정렬 - sort() 와 argsort()

### np.sort() 와 ndarray.sort()의 차이점
- np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None


In [14]:
org_array = np.array([3, 1, 9, 5])
print('org array:', org_array)

# np.sort()로 정렬
np_sort =  np.sort(org_array)
print('np_sort:', np_sort)
print('org_array after np_sort:', org_array)

# ndarray.sort()
nd_sort = org_array.sort()
print('org_array after ndarray.sort:', org_array)
print('nd_sort:', nd_sort)

# np.sort(), ndarray.sort() desc : [::-1] 
np_sort_desc = np.sort(org_array)[::-1]
print('np_sort desc:', np_sort_desc)

# 2d matrix sorting
array2d = np.array([[8,1],
                    [7, 12]])
np_sort_2d_axis0 = np.sort(array2d, axis=0)
print('row sorting:', np_sort_2d_axis0)

np_sort_2d_axis1 = np.sort(array2d, axis=1)
print('col sorting:', np_sort_2d_axis1)




org array: [3 1 9 5]
np_sort: [1 3 5 9]
org_array after np_sort: [3 1 9 5]
org_array after ndarray.sort: [1 3 5 9]
nd_sort: None
np_sort desc: [9 5 3 1]
row sorting: [[ 7  1]
 [ 8 12]]
col sorting: [[ 1  8]
 [ 7 12]]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


### 행렬의 인덱스 값 반환 정렬 - np.argsort()


In [15]:
# 정렬된 행렬의 인덱스 값 반환 - np.argsort()
org_array = np.array([3,1,9,5])
sort_index = np.argsort(org_array)[::-1] # desc
print(type(sort_index))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_index)

name_array = np.array(['john', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]
성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['john' 'sarah' 'samuel' 'mike' 'kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기


In [20]:
#행렬 내적(행렬 곱)
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[7, 8],
             [9, 10],
             [11, 12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

# 전치행렬 transpose()

a = np.array([[1, 2],
              [3, 4]])
transpose_a = np.transpose(a)
print('a 의 전치행렬:', transpose_a)

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])
transpose_b = np.transpose(b)
print('b의 전치행렬:', transpose_b)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
a 의 전치행렬: [[1 3]
 [2 4]]
b의 전치행렬: [[1 3 5]
 [2 4 6]]


# Pandas

## titanic 


In [21]:
# google drive 연결
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
import pandas as pd

train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/titanic/train.csv')
train.head(10)

# DF 크기 체크 : shape
print('df 크기:', train.shape)

# info
train.info()

#describe
train.describe()

# value_counts()
value_counts = train['Pclass'].value_counts()
print(value_counts)

# Series
titanic_pclass = train['Pclass']
print(type(titanic_pclass))
titanic_pclass.head(10)

df 크기: (891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>


0    3
1    1
2    3
3    1
4    3
5    3
6    1
7    3
8    3
9    2
Name: Pclass, dtype: int64