<a href="https://colab.research.google.com/github/johyunkang/py_pandas/blob/main/python_ml_guide_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3], [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)




array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1:1차원, array2:2차원, array3: 2차원
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


type 변경


In [2]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
print(array_float1)
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1.1 2.1 3.1]
[1 2 3] int32


**ndarray를 편리하게 생성하기 - arrange, zeros, ones**




In [3]:
# arange() TO 값까지
seq_array = np.arange(10)
print(seq_array)

# arange() from to
seq_array1 = np.arange(1, 10)
print(seq_array1)

# arange() from to interval
seq_array2 = np.arange(1,10, 2)
print(seq_array2)

print('--------------------------------------------------')
# zeros()
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print('zero_array type:', zero_array.dtype, 'shape:', zero_array.shape)

print('--------------------------------------------------')
# ones()
one_array = np.ones((3,2))
print(one_array)
print('ones type:', one_array.dtype, 'shape:', one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
--------------------------------------------------
[[0 0]
 [0 0]
 [0 0]]
zero_array type: int32 shape: (3, 2)
--------------------------------------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
ones type: float64 shape: (3, 2)


**차원과 크기를 변경하는 reshape()**

In [4]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

# -1 인자는 변경 가능한 숫자로 자동대입 
# reshape(2,5) 를 입력해야 하지만 열 인자에 5를 넣었을때 가능한 행 인자는 2 이기에 -1 이 2로 자동대입 됨
array4 = array1.reshape(-1,5)
print('array4:\n', array4)

array5 = array1.reshape(5,-1)
print('array5:\n', array5)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array5:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Indexing


In [5]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]
print('value:', value)
print(type(value))

array1[8] = 1
array1[7] = 5
print('array1:', array1)


array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('row=0, col=0 index 값:', array2d[0,0])
print('row=2, col=2 index 값:', array2d[2,2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
array1: [1 2 3 4 5 6 7 5 1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
row=0, col=0 index 값: 1
row=2, col=2 index 값: 9


## 행렬의 정렬 - sort() 와 argsort()

### np.sort() 와 ndarray.sort()의 차이점
- np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None


In [6]:
org_array = np.array([3, 1, 9, 5])
print('org array:', org_array)

# np.sort()로 정렬
np_sort =  np.sort(org_array)
print('np_sort:', np_sort)
print('org_array after np_sort:', org_array)

# ndarray.sort()
nd_sort = org_array.sort()
print('org_array after ndarray.sort:', org_array)
print('nd_sort:', nd_sort)

# np.sort(), ndarray.sort() desc : [::-1] 
np_sort_desc = np.sort(org_array)[::-1]
print('np_sort desc:', np_sort_desc)

# 2d matrix sorting
array2d = np.array([[8,1],
                    [7, 12]])
np_sort_2d_axis0 = np.sort(array2d, axis=0)
print('row sorting:', np_sort_2d_axis0)

np_sort_2d_axis1 = np.sort(array2d, axis=1)
print('col sorting:', np_sort_2d_axis1)




org array: [3 1 9 5]
np_sort: [1 3 5 9]
org_array after np_sort: [3 1 9 5]
org_array after ndarray.sort: [1 3 5 9]
nd_sort: None
np_sort desc: [9 5 3 1]
row sorting: [[ 7  1]
 [ 8 12]]
col sorting: [[ 1  8]
 [ 7 12]]


### 행렬의 인덱스 값 반환 정렬 - np.argsort()


In [7]:
# 정렬된 행렬의 인덱스 값 반환 - np.argsort()
org_array = np.array([3,1,9,5])
sort_index = np.argsort(org_array)[::-1] # desc
print(type(sort_index))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_index)

name_array = np.array(['john', 'mike', 'sarah', 'kate', 'samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]
성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['john' 'sarah' 'samuel' 'mike' 'kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기


In [8]:
#행렬 내적(행렬 곱)
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[7, 8],
             [9, 10],
             [11, 12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

# 전치행렬 transpose()

a = np.array([[1, 2],
              [3, 4]])
transpose_a = np.transpose(a)
print('a 의 전치행렬:', transpose_a)

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])
transpose_b = np.transpose(b)
print('b의 전치행렬:', transpose_b)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
a 의 전치행렬: [[1 3]
 [2 4]]
b의 전치행렬: [[1 3 5]
 [2 4 6]]


# Pandas

## titanic 


In [9]:
# google drive 연결
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:
import pandas as pd

train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/titanic/train.csv')
train.head(10)

# DF 크기 체크 : shape
print('df 크기:', train.shape)

# info
train.info()

#describe
train.describe()

# value_counts()
value_counts = train['Pclass'].value_counts()
print(value_counts)

# Series
titanic_pclass = train['Pclass']
print(type(titanic_pclass))
titanic_pclass.head(10)

df 크기: (891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>


0    3
1    1
2    3
3    1
4    3
5    3
6    1
7    3
8    3
9    2
Name: Pclass, dtype: int64

## DataFrame 과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

In [11]:
import numpy as np
import pandas as pd


col_name1=['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)

# 리스트 이용 DF 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DF:\n', df_list1)

# numpy ndarray 를 이용해 만든 DF
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DF:\n', df_array1)

# 2행 3열 DF
# 3개의 컬럼명이 필요
colname2 = ['col1', 'col2', 'col3']
list2 = np.random.randn(6).reshape(2,3)

array2 = np.array(list2)
print('array2 shape:', array2.shape)

df_list2 = pd.DataFrame(list2, columns=colname2)
print('2차원 리스트로 만든 DF:\n', df_list2)

df_array2 = pd.DataFrame(array2, columns=colname2)
print('2차원 ndarray로 만든 DF:\n', df_array2)

# 딕셔너리를 활용한 DF 생성
# key는 문자열 컬럼명으로 매핑, value는 리스트 형(또는 ndarray) 컬럼 데이터로 매핑
dict = {'col1':[1,11], 'col2':[2, 22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DF:\n', df_dict)

array1 shape: (3,)
1차원 리스트로 만든 DF:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DF:
    col1
0     1
1     2
2     3
array2 shape: (2, 3)
2차원 리스트로 만든 DF:
        col1      col2      col3
0 -0.018759  1.250985 -0.896735
1  1.047975  0.445989 -1.427814
2차원 ndarray로 만든 DF:
        col1      col2      col3
0 -0.018759  1.250985 -0.896735
1  1.047975  0.445989 -1.427814
딕셔너리로 만든 DF:
    col1  col2  col3
0     1     2     3
1    11    22    33


## DF를 넘파이 ndarray, 리스트, 딕셔너리로 변환하기

In [12]:
# DF를 ndarray로 변환
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

# DF를 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

# DF를 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]
df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


## DF에 컬럼 추가 및 수정

In [13]:
# Titanic DF에 'age_0' 컬럼 추가 및 0 값 할당
train['age_0'] = 0
train.head(10)

# 기존 컬럼을 이용한 신규 컬럼 생성
train['age_by_10'] = train['Age'] * 10
train['family_no'] = train['SibSp'] + train['Parch']+1
train.head(10)

# 기존 컬럼에 일괄적으로 100 값 업데이트
train['age_by_10'] = train['age_by_10'] + 100
train.head(10)

PassengerId  Survived  Pclass  ... age_0 age_by_10  family_no
0            1         0       3  ...     0     320.0          2
1            2         1       1  ...     0     480.0          2
2            3         1       3  ...     0     360.0          1
3            4         1       1  ...     0     450.0          2
4            5         0       3  ...     0     450.0          1
5            6         0       3  ...     0       NaN          1
6            7         0       1  ...     0     640.0          1
7            8         0       3  ...     0     120.0          5
8            9         1       3  ...     0     370.0          3
9           10         1       2  ...     0     240.0          2

[10 rows x 15 columns]

## DF 데이터 삭제

### DataFrame.drop() 설명
```python
DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
```

위 drop 파라미터 중 중요한 파라미터는 **labels, axis, inplace** 이다.
- labels : 
- axis : 값에 따라 특정 컬럼 또는 로우(row)를 드롭. (axis=0 은 row, axis=1 은 column)
- inplace : False 값이 default. False로 두면 자신의 DF에서는 해당 컬럼을 삭제하지 않고, 삭제된 결과 DF를 반환. True로 두면 자신의 DF에서 컬럼 삭제하고 결과 값 반환하지 않음
   > 주의 : inplace=True 후 자기 자신에게 결과 값 반환하면 None 이 반환되어서 DF 자체의 모든 값이 사라짐

In [14]:
# age_0 컬럼 삭제 (drop)
train_drop_age0 = train.drop('age_0', axis=1)
train_drop_age0.head(10)

# 여러 컬럼을 한 번에 삭제, inplace=True 라 결과값 반환하지 않음
train_drops = train.drop(['age_0', 'age_by_10', 'family_no'], axis=1, inplace=True)
print('train_drops 결과값:', train_drops)
train.head(10)



train_drops 결과값: None


PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]

In [15]:
# 행 삭제
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('### 행 삭제 전 DF ###')
print(train.head(3))

train.drop([0,1,2], axis=0, inplace=True)
print('#### 첫 3행 삭제 후 DF ###')
print(train.head(3))

### 행 삭제 전 DF ###
   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S

[3 rows x 12 columns]
#### 첫 3행 삭제 후 DF ###
   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q

[3 rows x 12 columns]


## 불린 인덱싱


In [21]:
# 60세 초과 리스트 뽑기
train_bool = train[train['Age'] > 60]
print(type(train_bool))
train_bool

# 60세 초과 승객 중 이름과 나이 컬럼 만 뽑기 (컬럼명을 배열 형식으로 넣어야 함)
train_nm_age = train[train['Age']> 60][['Name', 'Age']]
train_nm_age.head(20)

# 위와 동일(이름, 나이)하게 loc[] 를 이용하는 방법
train_nm_age2 = train.loc[train['Age'] > 60, ['Name', 'Age']]
train_nm_age2.head(20)

# 복합 조건. 나이 60 초과 & 1등급 선실 & 성별은 여성 승객 뽑기
train_multi_cond = train[(train['Age'] > 60) 
                       & (train['Pclass'] == 1)
                       & (train['Sex'] == 'female')
                        ]
train_multi_cond.head(10)

# 조건을 변수에 할당 하기
cond1 = train['Age'] > 60
cond2 = train['Pclass'] == 1
cond3 = train['Sex'] == 'female'
train_multi_cond2 = train[ cond1 & cond2 & cond3]
train_multi_cond2.head(10)

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
275          276         1       1  ...  77.9583    D7         S
829          830         1       1  ...  80.0000   B28       NaN

[2 rows x 12 columns]

## 정렬, Aggregation, Group by 적용
### sort_values()

In [23]:
# Name 컬럼으로 정렬하기
train_sort_by_name = train.sort_values(by=['Name'])
train_sort_by_name.head(10)

# Pclass, Name 으로 내림차순 정렬하기
train_multi_sort = train.sort_values(by=['Pclass', 'Name'], ascending=False)
train_multi_sort.head(10)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
868          869         0       3  ...   9.5000   NaN         S
153          154         0       3  ...  14.5000   NaN         S
282          283         0       3  ...   9.5000   NaN         S
286          287         1       3  ...   9.5000   NaN         S
559          560         1       3  ...  17.4000   NaN         S
422          423         0       3  ...   7.8750   NaN         S
240          241         0       3  ...  14.4542   NaN         C
111          112         0       3  ...  14.4542   NaN         C
495          496         0       3  ...  14.4583   NaN         C
354          355         0       3  ...   7.2250   NaN         C

[10 rows x 12 columns]

### Aggregation 함수
 min(), max(), sum(), count()

In [26]:
# count() - 모든 컬럼 별로 count 값이 출력 됨
train.count()

# 특정 컬럼 만 mean() 적용하기
train[['Age', 'Fare']].mean()



Age     29.703474
Fare    32.215643
dtype: float64

### groupby()

In [46]:
# groupby()를 사용하면 DataFrameGroupBy 객체를 반환함
train_groupby = train.groupby(by='Pclass')
print(type(train_groupby))
train_groupby.head(10)

# groupby 반환된 DF에 aggregation 함수를 호출하면 
# groupby() 대상 컬럼을 제외한 모든 컬럼에 해당 aggregation 함수를 적용함
train_grp_cnt = train_groupby.count()
print(train_grp_cnt)

# groupby() 반환된 DF 에 특정 컬럼만 aggregation 함수 적용하기
print('### 특정 컬럼만 Agg 함수 적용')
train_grp_cnt = train.groupby('Pclass')[['PassengerId', 'Survived']].count()
print(train_grp_cnt.head(3))

# 멀티 aggregation 함수 적용. Pclass 컬럼으로 groupby 된 컬럼 (Age, Fare)에 대해 min, max, mean, std 값 출력
print('#### 멀티 aggregation #############')
train_agg_multi = train.groupby('Pclass')[['Age', 'Fare']].agg([max, min, 'mean', 'std'])
print(train_agg_multi.head(3))

# 멀티 aggregation 함수 적용. 컬럼 별로 다른 agg 함수 적용
print('#### 멀티 aggregation 컬럼별로 다른 agg #############')
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
print(train.groupby('Pclass').agg(agg_format))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>
        PassengerId  Survived  Name  Sex  ...  Ticket  Fare  Cabin  Embarked
Pclass                                    ...                               
1               215       215   215  215  ...     215   215    175       213
2               184       184   184  184  ...     184   184     16       184
3               489       489   489  489  ...     489   489     12       489

[3 rows x 11 columns]
### 특정 컬럼만 Agg 함수 적용
        PassengerId  Survived
Pclass                       
1               215       215
2               184       184
3               489       489
#### 멀티 aggregation #############
         Age                                  Fare                           
         max   min       mean        std       max  min       mean        std
Pclass                                                                       
1       80.0  0.92  38.234703  14.843017  512.3292  0.0  84.214554  78.558341
2       70.0  0.67  

## 결손 데이터 처리하기
### isna(), fillna()

In [52]:
# isna() 로 결손 데이터 확인하기
print(train.isna().head(10))  # True / False 로 반환됨

# 결손 데이터 개수 구하기
print('결손 데이터 개수 구하기')
print(train.isna().sum())

# fillna()로 결손 데이터 대체하기
print('fillna()로 결손 데이터 대체하기. NaN 값을 C000 으로 대체')
train['Cabin'] = train['Cabin'].fillna('C000')
print(train.head(10))

# Age 컬럼 NaN 값을 평균으로 대체, Embarked 컬럼 NaN 을 S 로 대체
print('### Age 컬럼 NaN 값을 평균으로 대체, Embarked 컬럼 NaN 을 S 로 대체')
train['Age'] = train['Age'].fillna(train['Age'].mean())
train['Embarked'] = train['Embarked'].fillna('S')
print(train.isna().sum())

    PassengerId  Survived  Pclass   Name  ...  Ticket   Fare  Cabin  Embarked
3         False     False   False  False  ...   False  False  False     False
4         False     False   False  False  ...   False  False  False     False
5         False     False   False  False  ...   False  False  False     False
6         False     False   False  False  ...   False  False  False     False
7         False     False   False  False  ...   False  False  False     False
8         False     False   False  False  ...   False  False  False     False
9         False     False   False  False  ...   False  False  False     False
10        False     False   False  False  ...   False  False  False     False
11        False     False   False  False  ...   False  False  False     False
12        False     False   False  False  ...   False  False  False     False

[10 rows x 12 columns]
결손 데이터 개수 구하기
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age      

## apply lambda 식으로 데이터 가공

In [60]:
# square 함수를 lambda 식으로 변환
# 아래 lambda 식은 : 를 기준으로 왼쪽은 입력인자, 오른쪽은 계산 후 결과값
lambda_square = lambda x : x ** 2
print('3의 제곱은:', lambda_square(3))

# lambda 식을 이용해 여러 값을 인자로 받을 경우 map() 함수 사용
print('### lambda 식을 이용해 여러 값을 인자로 받을 경우 map() 함수 사용')
a = [1, 2, 3]
squares = map(lambda x : x ** 2, a)
print(list(squares))

# lambda 식에 if else 사용
print('### lambda 식에 if else 사용')
# if 절 전에 if조건 반환 값, else 절 후에 반환값. else if 는 사용 불가
train['Child_Adult'] = train['Age'].apply(lambda x : 'Child' if x <= 15 else 'Adult')
print(train[['Age', 'Child_Adult']].head(10))

# Age 15 이하는 Child, 15~60: Adult, 60 초과는 Elderly
print('### Age <= 15 : Child, 15~60: Adult, 60 초과는 Elderly')
train['Age_cat'] = train['Age'].apply(lambda x : 'Child' if x <= 15 else (
                                                                          'Adult' if x <= 60 else 'Elderly')
                                     )
print(train[['Age', 'Age_cat']].head(10))
print('value_counts():\n', train['Age_cat'].value_counts())




3의 제곱은: 9
### lambda 식을 이용해 여러 값을 인자로 받을 경우 map() 함수 사용
[1, 4, 9]
### lambda 식에 if else 사용
          Age Child_Adult
3   35.000000       Adult
4   35.000000       Adult
5   29.703474       Adult
6   54.000000       Adult
7    2.000000       Child
8   27.000000       Adult
9   14.000000       Child
10   4.000000       Child
11  58.000000       Adult
12  20.000000       Adult
### Age <= 15 : Child, 15~60: Adult, 60 초과는 Elderly
          Age Age_cat
3   35.000000   Adult
4   35.000000   Adult
5   29.703474   Adult
6   54.000000   Adult
7    2.000000   Child
8   27.000000   Adult
9   14.000000   Child
10   4.000000   Child
11  58.000000   Adult
12  20.000000   Adult
value_counts():
 Adult      783
Child       83
Elderly     22
Name: Age_cat, dtype: int64


In [62]:
# 나이에 따른 더 세분화된 함수
def get_category(age):
  cat = ''
  if age <= 5 : cat = 'Baby'
  elif age <= 12 : cat = 'Child'
  elif age <= 18 : cat = 'Teenager'
  elif age <= 25 : cat = 'Student'
  elif age <= 35 : cat = 'Young Adult'
  elif age <= 60 : cat = 'Adult'
  else: cat = 'Elderly'

  return cat

# get_category(X)는 입력값으로 Age 컬럼 값을 받아 해당하는 cat 반환
train['Age_Cat'] = train['Age'].apply(lambda x : get_category(x))
print(train[['Age', 'Age_cat', 'Age_Cat']].head(10))


          Age Age_cat      Age_Cat
3   35.000000   Adult  Young Adult
4   35.000000   Adult  Young Adult
5   29.703474   Adult  Young Adult
6   54.000000   Adult        Adult
7    2.000000   Child         Baby
8   27.000000   Adult  Young Adult
9   14.000000   Child     Teenager
10   4.000000   Child         Baby
11  58.000000   Adult        Adult
12  20.000000   Adult      Student
